# 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code that you can use to perform common tasks, operations, or functionalities without having to write the code from scratch. Libraries bundle together functions, classes, and modules that perform specific actions, making it easier for developers to build applications, analyze data, manipulate files, and much more.

Libraries can be thought of as tools or packages that extend Python’s capabilities, allowing you to accomplish tasks with less effort and time.




we use python libraries because of the following benefits


1. Code Reusability

: Libraries provide reusable code that can be utilized across multiple projects, reducing redundancy and saving time. For example, if you need to perform mathematical operations, you can use the math library instead of writing your own functions.

2. Simplify Complex Tasks:

 Python libraries encapsulate complex logic and algorithms, making it easier to perform advanced tasks. For instance, the NumPy library simplifies numerical computations, and Pandas makes data manipulation straightforward.

3. Improve Productivity:

 By using libraries, developers can focus on solving their specific problems without worrying about the underlying implementation of common tasks. This boosts productivity and accelerates development.

4. Community Support:

 Many Python libraries are developed and maintained by a community of developers. They are often well-documented, tested, and optimized, making them reliable and efficient to use.



 examples of python libraries are


NumPy:              Used for numerical computations and working with arrays.
Pandas:             Used for data manipulation and analysis.
Matplotlib:         Used for creating static, animated, and interactive visualizations in Python.
Flask:              A lightweight web framework for building web applications.
SciPy:              Used for scientific and technical computing.
TensorFlow:         Used for machine learning and deep learning applications.


#  2. What is the difference between Numpy array and List?

1. Data Structure:
NumPy Array:

A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers.
It can be multi-dimensional (1D, 2D, 3D, etc.), allowing for more complex data manipulation.

Python List:

A Python list is a collection of items that can be of different types (integers, strings, floats, etc.).
Lists are one-dimensional by default, though they can contain other lists to create nested structures.

2. Homogeneity:
NumPy Array:

All elements in a NumPy array must be of the same data type (e.g., all integers or all floats).
This homogeneity makes NumPy arrays more efficient for numerical operations.
Python List:


Python lists can contain elements of different data types (e.g., integers, strings, and floats in the same list).
This flexibility makes lists more versatile but less efficient for numerical computations.



3. Performance:
NumPy Array:

NumPy arrays are optimized for performance, especially with large datasets.
NumPy takes advantage of vectorization, allowing you to perform operations on entire arrays without the need for explicit loops.
Python List:

Python lists are slower than NumPy arrays when it comes to numerical operations, particularly with large datasets.
Lists require more overhead since they are dynamically typed and have to handle elements of varying types.



4. Memory Efficiency:
NumPy Array:

NumPy arrays are more memory-efficient because they store elements in contiguous blocks of memory.
This allows for better cache utilization and reduced memory overhead.
Python List:

Python lists use more memory because each element is an object with its own memory overhead.
Lists store references to objects, which can lead to increased memory usage.



5. Functionality:
NumPy Array:

NumPy arrays offer a wide range of mathematical operations, including element-wise operations, matrix operations, and broadcasting.
They support advanced functions such as linear algebra operations, Fourier transforms, and random sampling.
NumPy arrays can be reshaped, sliced, and indexed in ways that are not possible with Python lists.


Python List:

Lists support basic operations like addition, multiplication, slicing, and indexing, but they lack the advanced mathematical functions provided by NumPy.
Python lists are more flexible when it comes to holding and manipulating different types of data.


6. Usability:
NumPy Array:

NumPy is ideal for tasks that involve large-scale numerical data processing, such as scientific computing, data analysis, and machine learning.
NumPy requires importing the library (import numpy as np).
Python List:

Python lists are better suited for general-purpose programming tasks, where the data is heterogeneous or where complex numerical operations are not required.
Lists are built into Python and do not require any additional libraries.

#  3. Find the shape, size and dimension of the following array?
*  [[1, 2, 3, 4]
 * [5, 6, 7, 8],
 * [9, 10, 11, 12]]

In [236]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])


shape = array.shape


size = array.size

dimension = array.ndim

print(f"Shape: {shape}")
print(f"Size: {size}")
print(f"Dimension: {dimension}")


Shape: (3, 4)
Size: 12
Dimension: 2


# 4. Write python code to access the first row of the following array?
* [[1, 2, 3, 4]
* [5, 6, 7, 8],
* [9, 10, 11, 12]]

In [237]:
import numpy as np

arr=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])


# code to access the first row of the following array

first_row=arr[0]

print(f"first row in the given array is:   {first_row}")

first row in the given array is:   [1 2 3 4]


#  5. How do you access the element at the third row and fourth column from the given numpy array?
* [[1, 2, 3, 4]
* [5, 6, 7, 8],
* [9, 10, 11, 12]]

In [238]:
import numpy as np

arr=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])

element= arr[2,3]

print(f" element at the third row and fourth column is:          {element}")


 element at the third row and fourth column is:          12


#  6. Write code to extract all odd-indexed elements from the given numpy array?
* [[1, 2, 3, 4]
* [5, 6, 7, 8],
* [9, 10, 11, 12]]

In [240]:
# we can do this in two ways 

# 1 


import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Extract elements at odd indices
# For rows
odd_indexed_rows = array[1::2, :]  # Skip by 2 to get rows with odd indices
# For columns
odd_indexed_columns = array[:, 1::2]  # Skip by 2 to get columns with odd indices

print("Odd-indexed rows:\n", odd_indexed_rows)
print("Odd-indexed columns:\n", odd_indexed_columns)


Odd-indexed rows:
 [[5 6 7 8]]
Odd-indexed columns:
 [[ 2  4]
 [ 6  8]
 [10 12]]


In [241]:
# 2nd

import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Flatten the array to treat it as 1D
flattened_array = array.flatten()

# Extract elements at odd indices
odd_indexed_elements = flattened_array[1::2]

print("Odd-indexed elements:", odd_indexed_elements)


Odd-indexed elements: [ 2  4  6  8 10 12]


# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [242]:
import numpy as np 

arr=np.random.rand(3,3)
print(arr)

[[0.60526405 0.22631954 0.92802547]
 [0.62970904 0.72453669 0.03810994]
 [0.6705685  0.07477366 0.93674302]]


#  8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand

np.random.rand Generates random numbers from a uniform distribution over the interval [0, 1) 
All numbers in this range are equally likely to occur



np.random.randn


Generates random numbers from a standard normal distribution (mean 0 and standard deviation 1).
The distribution is bell-shaped, with most numbers clustered around the mean (0), and fewer numbers as you move away from the mean.



np.random.rand: When you need uniformly distributed random numbers in the range [0, 1).

np.random.randn: When you need normally distributed random numbers (e.g., for statistical modeling or simulations).





# 9. Write code to increase the dimension of the following array?
* [[1, 2, 3, 4]
* [5, 6, 7, 8],
* [9, 10, 11, 12]]

In [243]:
import numpy as np 

arr=np.array([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]])

print(f"dimesion of this array is:    {arr.ndim}")

dimesion of this array is:    2


In [244]:
# to increase dimention just put extra square breacket

import numpy as np 

arr1=np.array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]]])

print(f"dimesion of this array is:    {arr1.ndim}")

dimesion of this array is:    3


# 10. How to transpose the following array in NumPy?
* [[1, 2, 3, 4]
* [5, 6, 7, 8],
* [9, 10, 11, 12]]

In [245]:
import numpy as np 

arr=np.array ([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])


In [246]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [247]:
np.transpose(arr)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# 11. Consider the following matrix:
* Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
* Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]



* Perform the following operation using Python
 * Index wise multiplicatio
* Matrix multiplicatio
* Add both the matric
* Subtract matrix B from 
* Divide Matrix B by A

In [248]:
 
 #Index wise multiplication
 
 
import numpy as np 

met1= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
met2= np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])


# Add both the matric
result=met1*met2
print(F"metrix 1:\n\n {met1}\n -------------------------\n metrix 2: \n\n  {met2}\n--------------------------")
print(f"multiplication of both the metrix is: \n\n    {result}\n---------------------------")



 
 

metrix 1:

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 -------------------------
 metrix 2: 

  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------
multiplication of both the metrix is: 

    [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
---------------------------


In [249]:
#Matrix multiplication




import numpy as np 

met1= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
met2= np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])


met3= np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

met4= np.array([[1, 2],
                 [3, 4],
                 [5, 6],
                 [7, 8]])

result=met3 @ met4

print(F"metrix 1:\n\n {met1}\n -------------------------\n metrix 2: \n\n  {met2}\n--------------------------")





#print(f"metrix multiplication of both the metrix is: \n\n    {result}\n---------------------------")
print(f"here we can not able to do metrix multiplication  in this metrix because\n metrix rule is m*n = n*p  so we have to reshape accordingly \n")

print(F"new metrix 1:\n\n {met3}\n -------------------------\n new metrix 2: \n\n  {met4}\n--------------------------")

print(f"metrix multication of metrix one and two is: \n {result}")

metrix 1:

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 -------------------------
 metrix 2: 

  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------
here we can not able to do metrix multiplication  in this metrix because
 metrix rule is m*n = n*p  so we have to reshape accordingly 

new metrix 1:

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 -------------------------
 new metrix 2: 

  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------------------------
metrix multication of metrix one and two is: 
 [[ 50  60]
 [114 140]
 [178 220]]


In [250]:
# addition of metrix


import numpy as np 

met1= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
met2= np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])



added_met=met1+met2
print(F"metrix 1:\n\n {met1}\n -------------------------\n metrix 2: \n\n  {met2}\n--------------------------")
print(f"added of both the metrix is: \n\n    {added_met}\n---------------------------")




metrix 1:

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 -------------------------
 metrix 2: 

  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------
added of both the metrix is: 

    [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
---------------------------


In [251]:
# Subtract matrix B from a



 
 
import numpy as np 

met1= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
met2= np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])


result=met1 - met2
print(F"metrix 1:\n\n {met1}\n -------------------------\n metrix 2: \n\n  {met2}\n--------------------------")
print(f"multiplication of both the metrix is: \n\n    {result}\n---------------------------")



 
 

metrix 1:

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 -------------------------
 metrix 2: 

  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------
multiplication of both the metrix is: 

    [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
---------------------------


In [252]:
# Divide Matrix B by A 




 
 #Index wise multiplication
 
 
import numpy as np 

met1= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
met2= np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])


result=met1/met2
print(F"metrix 1:\n\n {met1}\n -------------------------\n metrix 2: \n\n  {met2}\n--------------------------")
print(f"multiplication of both the metrix is: \n\n    {result}\n---------------------------")



 
 

metrix 1:

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 -------------------------
 metrix 2: 

  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------
multiplication of both the metrix is: 

    [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
---------------------------


# 12.  Which function in Numpy can be used to swap the byte order of an array?

In [253]:
# Certainly! To swap the byte order of an array in NumPy, you use the .byteswap() method. Here’s a straightforward example:


import numpy as np

# Create an array with a specific data type (e.g., int16)
array = np.array([1, 256, 65536], dtype=np.int16)

# Display the original array
print("Original array:", array)

# Display the original byte order (for demonstration)
print("Original byte order (hex):", array.tobytes().hex() )

# Swap the byte order
swapped_array = array.byteswap()

# Display the swapped array
print("Swapped array:", swapped_array)

# Display the swapped byte order (for demonstration)
print("Swapped byte order (hex):", swapped_array.tobytes().hex())


Original array: [  1 256   0]
Original byte order (hex): 010000010000
Swapped array: [256   1   0]
Swapped byte order (hex): 000101000000


C:\Users\MERAJ UL ARFIN\AppData\Local\Temp\ipykernel_197176\1688016387.py:7: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 65536 to int16 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array = np.array([1, 256, 65536], dtype=np.int16)


#  13.  What is the significance of the np.linalg.inv function?

In [254]:

"""The np.linalg.inv function in NumPy computes the inverse of a square matrix.

Significance:
Inverse of a Matrix: If you have a matrix A, np.linalg.inv(A) gives you the matrix 𝐴−¹ such that A*A-¹ where I is the identity matrix.
"""


import numpy as np

# Define a 2x2 matrix
matrix = np.array([[1, 2],
                   [3, 4]])

# Compute its inverse
inverse_matrix = np.linalg.inv(matrix)

print("Inverse Matrix:")
print(inverse_matrix)



Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


# 14. What does the np.reshape function do, and how is it used?

In [255]:

"""The np.reshape function in NumPy changes the shape of an array without altering its data. This function is used to create a new view of the original array with a different shape, as long as the total number of elements remains the same.

"""

import numpy as np

# Original 1D array
array = np.array([1, 2, 3, 4, 5, 6])

# Reshape it into a 2D array with 3 rows and 2 columns
reshaped_array = np.reshape(array, (3, 2))

print(reshaped_array)


[[1 2]
 [3 4]
 [5 6]]


#  15. What is broadcasting in Numpy?

In [256]:

"""Broadcasting in NumPy is a feature that allows you to perform operations on arrays of different shapes without explicitly reshaping them.

How It Works:
Alignment: NumPy automatically aligns arrays of different shapes so that they can be operated on together.
Stretching: If one array is smaller, NumPy "stretches" it to match the shape of the larger array."""

# for example


import numpy as np

# 2D array
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1D array
array_1d = np.array([1, 0, 1, 0])

# Broadcasting adds the 1D array to each row of the 2D array
result = array_2d + array_1d

print(result)


[[ 2  2  4  4]
 [ 6  6  8  8]
 [10 10 12 12]]
